# Generated by Django 5.1.1 on 2024-10-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_contactmessage_rename_created_at_stock_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
    ]
