# Generated by Django 5.1.1 on 2024-10-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
