# Generated by Django 5.1.1 on 2024-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
