# Generated by Django 5.1.1 on 2024-10-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_storerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
