# Generated by Django 5.1.1 on 2024-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_stock_description_alter_store_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storerequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Store Request', 'verbose_name_plural': 'Store Requests'},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='status',
        ),
        migrations.RemoveField(
            model_name='store',
            name='type',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='owner_name',
            field=models.CharField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='item_name',
            field=models.CharField(default='default@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='request_id',
            field=models.AutoField(default='Default Owner', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='requested_by',
            field=models.CharField(default='000-000-0000', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
