# Generated by Django 5.1.1 on 2024-10-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_storerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default='default@example.com', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='owner_name',
            field=models.CharField(default='Default Owner', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='request_id',
            field=models.IntegerField(),
        ),
    ]
