# Generated by Django 5.1.1 on 2024-10-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_remove_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
    ]
