# Generated by Django 5.1.1 on 2024-10-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
