# Generated by Django 5.1.1 on 2024-10-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_stock_low_stock_threshold_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
