# Generated by Django 5.1.1 on 2024-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_stock_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_images/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
