# Generated by Django 5.1.1 on 2024-10-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_stock_image_alter_stock_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
    ]
